config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'

  get 'reviews/show'

root :to => 'welcome#index'
devise_for :users

resources :products do
  resources :reviews

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :is_admin?

  def is_admin?
    current_user && current_user.admin
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
    @user = current_user
  end

  def index
    @user = current_user
    @products = Product.all
  end

  def create
    @product = Product.create(product_params)
    redirect_to 'products/index'
  end

  def edit
  end

  def show
    @product = Product.find(params[:id])
  end

end

private

def product_params
  params.require(:product).permit(:name, :description, :image, current_user)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews.all
  end

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.save
      binding.pry
    redirect_to product_reviews_path
  end

  def show
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review deleted successfully!"
    redirect_to product_reviews_path(@product)
  end

end

def review_params
  params.require(:review).permit(:content, :product_id)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
   current_user && current_user.admin
 end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicycle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Bicyle Shop Name</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/products">Products</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if current_user %>
           <h4 style="margin-top:15px; color:lightgrey;"><%= current_user.email %> | <%= link_to "Sign out", '/users/sign_out', :method => :delete %></h4>

          <% else %>
           <%= link_to "Sign up", '/users/sign_up' %> | <span class="glyphicon glyphicon-log-in"></span><%= link_to "Sign in", '/users/sign_in' %>
          <% end %>

        </ul>
      </div>
    </nav>
  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, url: products_path, html: { multipart: true } do |f| %>
<%= f.file_field :image %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h3>Here are all the products!!</h3>

<% @products.each do |product| %>
  <%= image_tag product.image.url %>
  <p><%=link_to product.name, product_path(product) %></p>
  <hr>
<% end %>
<% if is_admin?  %>
<%= link_to 'Add New Product', new_product_path(@product) %>
<% end %>
<br>
<br>
<br>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container">

<h1><%= @product.name %> </h1>
<%= image_tag @product.image %>
<p><%= @product.description %></p>

<%= link_to 'See Reviews', product_reviews_path(@product,@review) %>
<br>

<%= link_to 'Add Review', new_product_review_path(@product,@review) %>
</div>
<br>
<br>

app/views/reviews/_form.html.erb
<%= form_for @review, url: product_reviews_path, html: { multipart: true } do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<div class="container">
<h3>Here are all the Reviews for this product!</h3>
<br>
<hr>
<% if @reviews.any? %>
<% @reviews.each do |review| %>
<p><%= link_to review.content, product_review_path(@product,review.id) %> </p>
<br>
<hr>
<% end %>
<% else %>
<p>There are no reviews yet!</p>
<% end %>

</div>

app/views/reviews/new.html.erb
<h1>new review</h1>
<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>Review Page</h1>
<%= @review.content  %>

<br>
<hr>
<% if is_admin?  %>
<%= link_to 'Delete Review',  product_review_path(@product), :data => {:confirm => "Are you sure?",                                           :method => "delete"}, :class=>"btn btn-danger"%>

<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 style="color:lightgrey;">Welcome!</h1>

</div>